language: c
sudo: false
before_install: 
  - apt-get update -q
  - apt-get install -y build-essential subversion libncurses5-dev zlib1g-dev gawk gcc-multilib flex git-core gettext quilt ccache libssl-dev xsltproc
compiler:
    - gcc
# Change this to your needs
script: ./build ar71xx
