sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t sudomesh/sudowrt .

script: 
  - travis_wait 120 docker run -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY sudomesh/sudowrt ar71xx
